### ISSUE TITLE
Missing keyword argument

### ISSUE THREAD

**Issue by bobthehuge** [RostanTabet/refery#3]
Bonjour

### Problème
 Dans **prettify.py:72**, les arguments donnés à `compare (compare_outputs)` sont dans le mauvais ordre.

### Solution(s)
**prettify.py:72** : `msg = compare(actual, expected)` => `msg = compare(expected, actual)` ou `msg = compare(actual=actual, expected=expected)`

**prettify.py:38-44** : `diff_lines = unified_diff(expected_lines, actual_lines ...)` =>`diff_lines = unified_diff(actual_lines, expected_lines ...)`

Cordialement,
Bob

**Comment by rostan-t** [comment]
Thanks for the bug report.

I will not address this now as I plan on rewriting the whole "prettify" part using [rich](https://github.com/Textualize/rich). If you need this to be fixed quickly, please feel free to open a pull request.
